---
- hosts: localhost
  vars:
    git_key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  tasks:

    - name: Install packages
      yum:
        name:
          - git
          - ansible
          - neovim
          - audacious
          - terminator
          - nautilus
          - gnome-keyring
          - xfce4-sensors-plugin
          - xfce4-cpugraph-plugin
          - xfce4-screenshooter
          - xfce4-screenshooter-plugin
          - sshfs
          - gvfs-smb
          - redshift
          - redshift-gtk
          - kernel-tools
      become: yes
      tags:
        - packages

    - name: Remove unwanted applications
      yum:
        name:
          - nano
          - geany
        state: absent
      become: yes
      tags:
        - packages

    - name: Create required user folders
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      with_items:
        - "src"
        - ".local/share/themes"

    - name: Install user shared assets
      copy:
        src: "{{ ansible_env.HOME }}/src/laptop-config/{{ item.src }}"
        dest: "{{ item.dst }}"
        remote_src: yes
      become: yes
      with_items:
        - src: "fonts/"
          dst: "/usr/share/fonts/"
        - src: "backgrounds/"
          dst: "/usr/share/backgrounds/"
    
    - name: Create symlinks
      file:
        path: "{{ ansible_env.HOME }}/{{ item.link_dst }}"
        src: "{{ ansible_env.HOME }}/{{ item.link_src }}"
        state: link
        force: yes
      with_items:
        - link_src: "src/laptop-config/xfce4"
          link_dst: ".config/xfce4"
        - link_src: "src/laptop-config/themes"
          link_dst: ".local/share/themes"
        - link_src: "src/laptop-config/.bashrc"
          link_dst: ".bashrc"
        - link_src: "src/laptop-config/nvim"
          link_dst: ".config/nvim"
        - link_src: "src/laptop-config/terminator"
          link_dst: ".config/terminator"
        - link_src: "src/laptop-config/audacious"
          link_dst: ".config/audacious"
        - link_src: "src/laptop-config/applications"
          link_dst: ".local/share/applications"

    - name: Set LightDM background image
      lineinfile:
        path: "/etc/lightdm/lightdm-gtk-greeter.conf"
        regexp: '^background ?='
        line: "background=/usr/share/backgrounds/fedora1.jpg"
      become: yes
