---
- hosts: localhost
  vars:
    git_key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  tasks:
    - name: Install dependencies
      yum:
        name:
          - git
          - ansible
          - neovim
          - audacious
          - terminator
      become: yes

    - name: Create required user folders
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      with_items:
        - "src"
        - ".local/share/themes"

    #- name: Checkout config repo
    #  git:
    #    repo: "git@github.com:zedr/laptop-config.git"
    #    dest: "{{ ansible_env.HOME }}/src/laptop-config"
    #    track_submodules: yes
    #    key_file: "{{ git_key_file }}"

    - name: Install user fonts
      copy:
        src: "{{ ansible_env.HOME }}/src/laptop-config/fonts/"
        dest: "/usr/share/fonts/"
        remote_src: yes
      become: yes
    
    - name: Create symlinks
      file:
        path: "{{ ansible_env.HOME }}/{{ item.link_dst }}"
        src: "{{ ansible_env.HOME }}/{{ item.link_src }}"
        state: link
        force: yes
      with_items:
        - link_src: "src/laptop-config/xfce4"
          link_dst: ".config/xfce4"
        - link_src: "src/laptop-config/themes"
          link_dst: ".local/share/themes"
        - link_src: "src/laptop-config/.bashrc"
          link_dst: ".bashrc"
        - link_src: "src/laptop-config/nvim"
          link_dst: ".config/nvim"

        
