---
- hosts: localhost
  tasks:

    - name: Define Fedora major version number
      set_fact:
        fedora_version: "{{ hostvars['localhost'].ansible_distribution_major_version }}"
      tags:
        - packages

    - name: Check for RPM Fusion repo
      stat:
        path: '/etc/yum.repos.d/rpmfusion-free.repo'
      register: rpmfusion_repo
      tags:
        - packages

    - name: Install dependencies
      yum:
        disable_gpg_check: yes
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"

      become: yes
      when: not rpmfusion_repo.stat.exists
      tags:
        - packages

    - name: Install home packages
      yum:
        name:
          - vlc
          - python-vlc
          - ffmpeg
      become: yes
      tags:
        - packages

    - name: Remove unwanted applications
      yum:
        name:
          - parole
        state: absent
      become: yes
      tags:
        - packages
