---
- hosts: localhost
  tasks:

    - name: Install Rhythmbox and plugin dependencies
      become: yes
      dnf:
        name:
          - rhythmbox
          - python3-gobject
          - python3-cairo-devel
          - gobject-introspection-devel
          - cairo-gobject-devel

    - name:
      pip:
        name:
          - vext
          - vext.gi
          - PyGObject

    - name: Define the Rhythmbox plugins directory path
      set_fact:
        rhythmbox_plugins_path: "{{ ansible_env.HOME}}/.local/share/rhythmbox/plugins"

    - name: Ensure the Rhythmbox plugins directory exists
      file:
        state: directory
        path: "{{ rhythmbox_plugins_path }}"
        mode: 0755

    - name: Install tray icon plugin
      unarchive:
        src: https://github.com/mendhak/rhythmbox-tray-icon/raw/master/rhythmbox-tray-icon.zip
        remote_src: yes
        dest: "{{ rhythmbox_plugins_path }}"
