---
- hosts: localhost
  become: yes
  tasks:

    - name: Install Tuned
      yum:
        name:
          - tuned
          - tuned-utils
          - powertop
        state: present

    - name:
      systemd:
        name: tuned
        state: started
